"""second try

Revision ID: dfa93adcffbe
Revises: 
Create Date: 2025-05-01 15:38:01.582964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa93adcffbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('chef_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('chef_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chef_id'),
    sa.UniqueConstraint('chef_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cusine', sa.Enum('ITALIAN', 'CHINESE', 'INDIAN', 'MEXICAN', 'FRENCH', name='cuisine'), nullable=False),
    sa.Column('ingredients', sa.String(length=1000), nullable=False),
    sa.Column('cooking_instructions', sa.String(length=2000), nullable=False),
    sa.Column('date_of_publish', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('recipe_image',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('recipe_review',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('chef_id', sa.Uuid(), nullable=False),
    sa.Column('comment_description', sa.String(length=300), nullable=False),
    sa.Column('date_of_publish', sa.DateTime(), nullable=False),
    sa.Column('ratings', sa.Enum('EXCELLENT', 'VERY_GOOD', 'SATISFACTORY', 'DISAPPOINTING', 'UNPALATABLE', name='ratings'), nullable=False),
    sa.Column('vote_type', sa.Enum('LIKE', 'DISLIKE', name='votetype'), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['chef.chef_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('chef_id'),
    sa.UniqueConstraint('recipe_id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_review')
    op.drop_table('recipe_image')
    op.drop_table('recipe')
    op.drop_table('chef')
    # ### end Alembic commands ###
